CREATE TABLE ADDRESSES
(
	ADDRESSID INT PRIMARY KEY IDENTITY(1,1),
	STREETADDRESS VARCHAR(100) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	[STATE] VARCHAR(50),
	COUNTRY VARCHAR(50) NOT NULL,
	CUSTOMERID BIGINT
	FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	USERID INT
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)

select * from ADDRESSES

INSERT INTO ADDRESSES(STREETADDRESS, CITY, [STATE], COUNTRY, USERID)
VALUES ('P-162 Lasani Garden, Daewoo Road', 'Faisalabad', 'Punjab', 'Pakistan', 69)