CREATE TABLE EMPLOYEEUSERS
(
	EMPLOYEEID INT PRIMARY KEY IDENTITY(1,1),
	EMPLOYEEROLE VARCHAR(30) NOT NULL,
	USERID INT
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)


SELECT * FROM EMPLOYEEUSERS


DELETE FROM EMPLOYEEUSERS

INSERT INTO EMPLOYEEUSERS (EMPLOYEEROLE, USERID)
SELECT 'admin', USERID 
FROM USERS
WHERE USERTYPE = 'Employee'


update EMPLOYEEUSERS
SET EMPLOYEEROLE = 'Admin' WHERE USERID in (36,40)
