CREATE TABLE EMPLOYEEUSERS
(
	EMPLOYEEID INT PRIMARY KEY IDENTITY(1,1),
	EMPLOYEEROLE VARCHAR(30) NOT NULL,
	USERID INT
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)


SELECT * FROM EMPLOYEEUSERS

INSERT INTO EMPLOYEEUSERS (EMPLOYEEROLE, USERID)
VALUES ('Admin', 69)