CREATE PROCEDURE GetImageData
	@ModelId INT = 1

AS
BEGIN
	DECLARE @RecordsCount INT = (SELECT COUNT(*) FROM IMAGES WHERE MODELID = @ModelId);
	IF @RecordsCount = 0
	BEGIN
		SELECT IMAGEDATA, CONTENTTYPE, MODELID FROM IMAGES WHERE IMAGEID = 1;
	END
	ELSE
	BEGIN
		SELECT IMAGEDATA, CONTENTTYPE, MODELID FROM IMAGES WHERE IMAGEID = @ModelId;
	END
END


EXEC GetImageData @ModelId = 4