CREATE TABLE ORDERS
(
	ORDERID INT PRIMARY KEY IDENTITY(1,1),
	PLACEDBY INT NOT NULL
	FOREIGN KEY (PLACEDBY) REFERENCES USERS(USERID),
	CUSTOMERTYPE VARCHAR(50) NOT NULL, --user,customer
	ORDERDATETIME DATETIME NOT NULL,
	PAYMENTMETHOD VARCHAR(50) NOT NULL,
	CUSTOMERID BIGINT
	FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
	USERID INT,
	ADDDRESSID INT NOT NULL
	FOREIGN KEY (ADDDRESSID) REFERENCES ADDRESSES(ADDRESSID),
	ORDERSTATUS VARCHAR(50) NOT NULL
)


ALTER TABLE ORDERS
ALTER COLUMN 


UPDATE ORDERS
SET ORDERSTATUS = 'initiated'

SELECT *  FROM ORDERS


INSERT INTO ORDERS(PLACEDBY, CUSTOMERTYPE, ORDERDATETIME, PAYMENTMETHOD, USERID, ADDDRESSID, ORDERSTATUS)
VALUES (69, 'user', SYSDATETIME(), 'Cash', 69, 1, 'shipped')


