CREATE TABLE ORDERITEMS
(
	ITEMID INT PRIMARY KEY IDENTITY(1,1),
	VARIANTID INT NOT NULL
	FOREIGN KEY (VARIANTID) REFERENCES VARIANT(VARIANTID),
	QUANTITY INT NOT NULL,
	UNITPRICE DECIMAL(20,2) NOT NULL,
	ORDERID INT NOT NULL
	FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)

SELECT * FROM ORDERITEMS

INSERT INTO ORDERITEMS(VARIANTID, QUANTITY, UNITPRICE, ORDERID)
VALUES (1245, 8, (SELECT RETAILPRICE FROM VARIANT WHERE VARIANTID = 1245), 4)

SELECT * FROM VARIANT WHERE VARIANTID = 584