SELECT * FROM VARIANT

select * from MODEL where MODELID = 18

select * from BRANDS where BRANDID = 4

BEGIN TRANSACTION
update VARIANT
set VARIANTNAME = REPLACE(VARIANTNAME, (SELECT DISPLAY_NAME FROM BRANDS WHERE BRANDID = (SELECT BRANDID FROM MODEL WHERE MODEL.MODELID = VARIANT.MODELID)), '');

update VARIANT
set VARIANTNAME = TRIM(VARIANTNAME);

update VARIANT
set VARIANTNAME = REPLACE(VARIANTNAME,  (SELECT MODEL_NAME FROM MODEL WHERE MODEL.MODELID = VARIANT.MODELID), '');

update VARIANT
set VARIANTNAME = TRIM(VARIANTNAME);

