

CREATE TABLE USERS
(
	USERID INT PRIMARY KEY IDENTITY(1,1),
	USERNAME VARCHAR(50) NOT NULL,
	[PASSWORD] VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	FIRSTNAME VARCHAR(20) NOT NULL,
	LASTNAME VARCHAR(20),
	[DESCRIPTION] VARCHAR(200),
	REGISTERATION_DATE DATE NOT NULL,
	
)