

CREATE TABLE VARIANT
(
	VARIANTID INT PRIMARY KEY IDENTITY(1,1),
	VARIANTNAME VARCHAR(50) NOT NULL,
	RAM INT NOT NULL,
	STORAGE INT NOT NULL,
	COLOR VARCHAR(30) NOT NULL,
	RETAILPRICE DECIMAL(20,2) NOT NULL,
	WHOLESALEPRICE DECIMAL(20,2) NOT NULL
)


SELECT * FROM VARIANT

