

CREATE TABLE VARIANT
(
	VARIANTID INT PRIMARY KEY IDENTITY(1,1),
	VARIANTNAME VARCHAR(50) NOT NULL,
	RAM INT NOT NULL,
	STORAGE INT NOT NULL,
	COLOR VARCHAR(30) NOT NULL,
	RETAILPRICE DECIMAL(20,2) NOT NULL,
	WHOLESALEPRICE DECIMAL(20,2) NOT NULL,
	MODELID INT NOT NULL
	FOREIGN KEY (MODELID) REFERENCES MODEL(MODELID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)


ALTER TABLE VARIANT
ADD MODELID INT
FOREIGN KEY (MODELID) REFERENCES MODEL(MODELID)
ON DELETE CASCADE
ON UPDATE CASCADE




SELECT * FROM VARIANT where VARIANTNAME like '%iphone 14 pro%' and VARIANTNAME not like '%max%'

BEGIN TRANSACTION

UPDATE VARIANT
SET MODELID = ()

rollback

commit

SELECT MODEL.MODELID FROM MODEL, VARIANT WHERE VARIANT.VARIANTNAME LIKE '%' + MODEL_NAME + '%'

select * from model where MODEL_NAME like '%iphone 14 pro'


Begin Transaction
update VARIANT
set MODELID = 
(SELECT MODEL.MODELID)
FROM VARIANT, MODEL
WHERE VARIANTNAME LIKE '%' + MODEL_NAME + '%' 
AND VARIANTNAME NOT LIKE '%max%' 
AND VARIANTNAME NOT LIKE '%pro%' 
AND VARIANTNAME NOT LIKE '%ultra%' 
AND VARIANTNAME NOT LIKE '%5a%'
AND VARIANTNAME NOT LIKE '%Nord2%'
AND VARIANTNAME NOT LIKE '%Xperia 1 II%'

BEGIN TRANSACTION

Declare @Mname Varchar(50);
SET @Mname = 'Sony Xperia 1 III';
update VARIANT
set MODELID = 
(SELECT MODEL.MODELID from MODEL where MODEL_NAME like @Mname)
WHERE VARIANTNAME LIKE '%' + @Mname +'%' 
SELECT * FROM VARIANT where MODELID is null order by VARIANTID