SELECT * FROM BRANDS;

INSERT INTO BRANDS(BNAME)
VALUES ('DELL')

INSERT INTO BRANDCONTACTS(PHONENO, BRANDID)
VALUES('03046751252',1)

SELECT BRANDCONTACTS.ID, BRANDCONTACTS.PHONENO, BRANDS.BNAME
FROM BRANDCONTACTS
FULL OUTER JOIN BRANDS ON BRANDCONTACTS.BRANDID=BRANDS.ID;



SELECT BRANDCONTACTS.ID AS CONTACTID, BRANDCONTACTS.PHONENO, BRANDS.BNAME
FROM BRANDS
LEFT JOIN BRANDCONTACTS ON BRANDCONTACTS.BRANDID=BRANDS.ID;



SELECT BRANDCONTACTS.ID, BRANDCONTACTS.PHONENO, BRANDS.BNAME
FROM BRANDCONTACTS
INNER JOIN BRANDS ON BRANDCONTACTS.BRANDID=BRANDS.ID;

SELECT * FROM BRANDCONTACTS


SELECT A.PHONENO,A.BRANDID,A.BRANDID
FROM BRANDCONTACTS AS A, BRANDCONTACTS AS B
WHERE A.BRANDID = B.BRANDID
ORDER BY A.BRANDID



SELECT BRANDCONTACTS.PHONENO, BRANDS.BNAME AS [NAME]
FROM BRANDCONTACTS
INNER JOIN BRANDS ON BRANDS.ID = BRANDCONTACTS.BRANDID
UNION
SELECT SUPPLIERCONTACTS.PHONENO, SUPPLIER.SNAME AS [NAME]
FROM SUPPLIERCONTACTS
INNER JOIN SUPPLIER ON SUPPLIER.ID = SUPPLIERCONTACTS.SUPPLIERID
ORDER BY [NAME]



SELECT BRANDCONTACTS.BRANDID, COUNT(PHONENO) AS COUNTS
FROM BRANDCONTACTS
GROUP BY BRANDID

SELECT * INTO BRANDSBACKUP
FROM BRANDS


SELECT * FROM BRANDSBACKUP

DROP TABLE BRANDSBACKUP


SELECT BNAME, ID
FROM BRANDS
WHERE ID = (SELECT MAX(ID) FROM BRANDS);


SELECT BNAME, BRANDS.ID, ISNULL(BRANDCONTACTS.PHONENO, 'NOT FOUND') 
FROM BRANDS
LEFT JOIN BRANDCONTACTS ON BRANDCONTACTS.BRANDID = BRANDS.ID


SELECT * INTO BRANDSCOPY FROM BRANDS 


SELECT * FROM BRANDSCOPY

ALTER TABLE BRANDSCOPY
ADD ABC DECIMAL(4,2)

UPDATE BRANDSCOPY
SET ABC = 12.4

ALTER TABLE BRANDSCOPY
ALTER COLUMN ABC INT

