USE[Inventory_Management_System]

CREATE TABLE BATCH
(
	BATCHID INT PRIMARY KEY IDENTITY(1,1),
	BATCHNO INT NOT NULL,
	VARIANTID INT NOT NULL,
	QUNATITY INT NOT NULL,
	SUPPLIERID INT NOT NULL,
	SHIPMENTID INT NOT NULL,
	RELEASEDATE DATE NOT NULL,
	MANUFACTURERID INT NOT NULL
)

DROP TABLE BATCH

INSERT INTO BATCH(BATCHNO, VARIANTID, QUNATITY, SUPPLIERID, SHIPMENTID, RELEASEDATE, MANUFACTURERID)
VALUES
		(1,1,100,1,1,'05/27/2024', 1),
		(2,2,50000,1,1,'12/27/2024', 1)


SELECT * FROM BATCH;

SELECT COUNT(*) AS COUNTS FROM MODEL;

CREATE PROCEDURE GetAllBatches
AS
BEGIN
		SELECT * FROM BATCH;
END
GO

CREATE PROCEDURE GetBatchByBatchID
	@Id INT
AS
BEGIN
		SELECT * FROM BATCH WHERE BATCHID = @Id;
End
Go

CREATE PROCEDURE AddBatch
	@BatchNo INT,@VariantId INT,@Quantity BIGINT,@SupplierId INT,@ShipmentId INT,@ReleaseDate DATE,@ManufacturerId INT
AS
BEGIN
		INSERT INTO BATCH (BATCHNO, VARIANTID, QUNATITY, SUPPLIERID, SHIPMENTID, RELEASEDATE, MANUFACTURERID)
		VALUES(@BatchNo, @VariantId, @Quantity, @SupplierId, @ShipmentId, @ReleaseDate, @ManufacturerId)
End
Go

CREATE PROCEDURE UpdateBatch
	@Id INT,@Mname VARCHAR(50),@ReleaseDate DATE,@BrandId INT
AS
BEGIN
		UPDATE MODEL
		SET MNAME = @Mname, RELEASEDATE = @ReleaseDate, BRANDID = @BrandId
		WHERE ID = @Id;
End
Go


CREATE PROCEDURE DeleteModel
	@Id INT
AS
BEGIN
		DELETE FROM MODEL WHERE ID = @Id
End
Go
