USE[Inventory_Management_System]

CREATE TABLE BRANDCONTACTS
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PHONENO VARCHAR(11) NOT NULL,
	BRANDID INT NOT NULL
)

INSERT INTO BRANDCONTACTS(PHONENO,BRANDID)
VALUES
		('03128541627', 1),
		('03128541628', 1),
		('03417435942', 2),
		('03417415542', 3),
		('03417415543', 3),
		('03445315942', 4)


SELECT * FROM BRANDCONTACTS;

SELECT COUNT(*) AS COUNTS FROM BRANDCONTACTS;

CREATE PROCEDURE GetAllBrandsContacts
AS
BEGIN
		SELECT * FROM BRANDCONTACTS;
END
GO

CREATE PROCEDURE GetBrandContactsByBrandID
	@BrandId INT
AS
BEGIN
		SELECT * FROM BRANDCONTACTS WHERE BRANDID = @BrandId;
End
Go

CREATE PROCEDURE AddBrandContact
	@BrandId INT,@PhoneNo VARCHAR(11)
AS
BEGIN
		INSERT INTO BRANDCONTACTS(BRANDID, PHONENO)
		VALUES(@BrandId,@PhoneNo)
End
Go

CREATE PROCEDURE UpdateBrandContact
	@Id INT,@BrandId INT,@PhoneNo VARCHAR(11)
AS
BEGIN
		UPDATE BRANDCONTACTS
		SET BRANDID = @BrandId, PHONENO = @PhoneNo
		WHERE ID = @Id;
End
Go


CREATE PROCEDURE DeleteBrandContact
	@Id INT
AS
BEGIN
		DELETE FROM BRANDCONTACTS WHERE ID = @Id
End
Go
