USE[Inventory_Management_System]

CREATE TABLE MODEL
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MNAME VARCHAR(50) NOT NULL,
	RELEASEDATE DATE NOT NULL,
	BRANDID INT NOT NULL
)

INSERT INTO MODEL(MNAME,RELEASEDATE, BRANDID)
VALUES
		('Iphone 10', '05/27/2024', 1),
		('S22', '01/10/2024', 2),
		('NOTE 12', '09/21/2023', 3)


SELECT * FROM MODEL;


SELECT COUNT(*) AS COUNTS FROM MODEL;

CREATE PROCEDURE GetAllMODELS
AS
BEGIN
		SELECT * FROM MODEL;
END
GO

CREATE PROCEDURE GetModelByID
	@Id INT
AS
BEGIN
		SELECT * FROM MODEL WHERE ID = @Id;
End
Go

CREATE PROCEDURE AddModel
	@Mname VARCHAR(50),@ReleaseDate DATE,@BrandId INT
AS
BEGIN
		INSERT INTO MODEL(MNAME, RELEASEDATE, BRANDID)
		VALUES(@Mname, @ReleaseDate, @BrandId)
End
Go

CREATE PROCEDURE UpdateModel
	@Id INT,@Mname VARCHAR(50),@ReleaseDate DATE,@BrandId INT
AS
BEGIN
		UPDATE MODEL
		SET MNAME = @Mname, RELEASEDATE = @ReleaseDate, BRANDID = @BrandId
		WHERE ID = @Id;
End
Go


CREATE PROCEDURE DeleteModel
	@Id INT
AS
BEGIN
		DELETE FROM MODEL WHERE ID = @Id
End
Go
