USE[Inventory_Management_System]

CREATE TABLE SPECIFICATIONS
(
	MODELID INT PRIMARY KEY,
	SCREENSIZE DECIMAL(4,2) NOT NULL,
	BATTERY INT NOT NULL,
	SIMSLOTS INT NOT NULL
)

INSERT INTO SPECIFICATIONS(MODELID, SCREENSIZE, BATTERY, SIMSLOTS)
VALUES
		(1, 6.2, 45 , 1),
		(2, 6.8, 50 , 2),
		(3, 5.9, 55 , 2)


SELECT * FROM SPECIFICATIONS;

DROP TABLE SPECIFICATIONS

SELECT COUNT(*) AS COUNTS FROM MODEL;

CREATE PROCEDURE GetAllSpecifications
AS
BEGIN
		SELECT * FROM SPECIFICATIONS;
END
GO

EXEC GetAllSpecifications

CREATE PROCEDURE GetSpecificationsByModelId
	@ModelId INT
AS
BEGIN
		SELECT * FROM SPECIFICATIONS WHERE MODELID = @ModelId;
End
Go

CREATE PROCEDURE AddSpecifications
	@ModelId INT,@ScreenSize DECIMAL(4,2), @Battery INT,@SimSlots INT
AS
BEGIN
		INSERT INTO SPECIFICATIONS(MODELID, SCREENSIZE, BATTERY , SIMSLOTS)
		VALUES(@ModelId, @ScreenSize, @Battery, @SimSlots)
End
Go

CREATE PROCEDURE UpdateSpecifications
	@ModelId INT,@ScreenSize DECIMAL(4,2), @Battery INT,@SimSlots INT
AS
BEGIN
		UPDATE SPECIFICATIONS
		SET SCREENSIZE = @ScreenSize, BATTERY = @Battery, SIMSLOTS = @SimSlots
		WHERE MODELID = @ModelId;
End
Go


CREATE PROCEDURE DeleteSpecifications
	@ModelId INT
AS
BEGIN
		DELETE FROM SPECIFICATIONS WHERE MODELID = @ModelId
End
Go
