USE[Inventory_Management_System]

CREATE TABLE SUPPLIERCONTACTS
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PHONENO VARCHAR(11) NOT NULL,
	SUPPLIERID INT NOT NULL
)

INSERT INTO SUPPLIERCONTACTS(PHONENO,SUPPLIERID)
VALUES
		('03128541627', 1),
		('03128541628', 1),
		('03417435942', 2),
		('03417415542', 2),
		('03417415543', 3),
		('03445315942', 3)


SELECT * FROM SUPPLIERCONTACTS;

SELECT COUNT(*) AS COUNTS FROM SUPPLIERCONTACTS;

CREATE PROCEDURE GetAllSuppliersContacts
AS
BEGIN
		SELECT * FROM SUPPLIERCONTACTS;
END
GO

CREATE PROCEDURE GetSupplierContactsBySupplierID
	@SupplierId INT
AS
BEGIN
		SELECT * FROM SUPPLIERCONTACTS WHERE SUPPLIERID = @SupplierId;
End
Go

CREATE PROCEDURE AddSupplierContact
	@SupplierId INT,@PhoneNo VARCHAR(11)
AS
BEGIN
		INSERT INTO SUPPLIERCONTACTS(SUPPLIERID, PHONENO)
		VALUES(@SupplierId,@PhoneNo)
End
Go

CREATE PROCEDURE UpdateSupplierContact
	@Id INT,@SupplierId INT,@PhoneNo VARCHAR(11)
AS
BEGIN
		UPDATE SUPPLIERCONTACTS
		SET SUPPLIERID = @SupplierId, PHONENO = @PhoneNo
		WHERE ID = @Id;
End
Go


CREATE PROCEDURE DeleteSupplierContact
	@Id INT
AS
BEGIN
		DELETE FROM SUPPLIERCONTACTS WHERE ID = @Id
End
Go
