USE[Inventory_Management_System]

CREATE TABLE SUPPLIER
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	SNAME VARCHAR(50) NOT NULL,
	PHONENO VARCHAR(11) NOT NULL,
	SADDRESS VARCHAR(200) NOT NULL
)

INSERT INTO SUPPLIER(SNAME,PHONENO, SADDRESS)
VALUES
		('TCS', '03041325842', 'XXX'),
		('LEOPARD', '03041327412', 'XXX'),
		('POST', '03041315452', 'XXX')


SELECT * FROM SUPPLIER;


SELECT COUNT(*) AS COUNTS FROM SUPPLIER;

CREATE PROCEDURE GetAllSupplier
AS
BEGIN
		SELECT * FROM SUPPLIER;
END
GO

CREATE PROCEDURE GetSupplierByID
	@Id INT
AS
BEGIN
		SELECT * FROM SUPPLIER WHERE ID = @Id;
End
Go

CREATE PROCEDURE AddSupplier
	@Sname VARCHAR(50),@PhoneNo VARCHAR(11),@SAddress VARCHAR(200)
AS
BEGIN
		INSERT INTO SUPPLIER(SNAME, PHONENO, SADDRESS)
		VALUES(@Sname, @PhoneNo, @SAddress)
End
Go

CREATE PROCEDURE UpdateSupplier
	@Id INT,@Sname VARCHAR(50),@PhoneNo VARCHAR(11),@SAddress VARCHAR(200)
AS
BEGIN
		UPDATE SUPPLIER
		SET SNAME = @Sname, PHONENO = @PhoneNo, SADDRESS = @SAddress
		WHERE ID = @Id;
End
Go


CREATE PROCEDURE DeleteSupplier
	@Id INT
AS
BEGIN
		DELETE FROM SUPPLIER WHERE ID = @Id
End
Go
